apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer # !!! by default its ClusterIP
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 50042
      targetPort: 50042
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: blob-store
          image: europe-central2-docker.pkg.dev/blobs-project-449409/repo/blob-store:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50042
          command: ["./build/bin/frontend"]
          env:
            - name: MASTERS_COUNT
              value: "3"
            - name: CONTAINER_PORT
              value: "50042"
          resources:
            limits:
              ephemeral-storage: 1Gi
            requests:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 2Gi
