apiVersion: v1
kind: Service
metadata:
  name: master-service # SERVICE_NAME
  labels:
    app: master
spec:
  ports:
    - port: 50042
      targetPort: 50042
      name: master
  clusterIP: None # -> headless service -> DNS for each: master-service-0, master-service-1, ...
  selector:
    app: master
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: master # STATEFULSET_NAME
spec:
  selector:
    matchLabels:
      app: master # APP_LABEL_NAME # Matches the Service's selector
  serviceName: "master-service" # "SERVICE_NAME"
  replicas: 1 # NUMBER_OF_REPLICAS
  template:
    metadata:
      labels:
        app: master # APP_LABEL_NAME
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: blob-store
          image: europe-central2-docker.pkg.dev/blobs69/blob-repository/blob-store:v1.0.70
          imagePullPolicy: Always
          ports:
            - containerPort: 50042 # needs to match the MASTER port
              name: master
          command: ["./build/bin/master_server"]
          env:
            - name: CONTAINER_PORT
              value: "50042"
    #          volumeMounts:
#            - name: www
#              mountPath: CONTAINER_STORAGE_VOLUME_PATH
#  volumeClaimTemplates:
#    - metadata:
#        name: www
#      spec:
#        accessModes: [ "ReadWriteOnce" ]
#        resources:
#          requests:
#            storage: 1Gi