apiVersion: v1
kind: Service
metadata:
  name: worker-service # SERVICE_NAME
  labels:
    app: worker
spec:
  ports:
    - port: 50042
      targetPort: 50042
  clusterIP: None # -> headless service -> DNS for each: worker-service-0, worker-service-1, ...
  selector:
    app: worker
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: worker # STATEFULSET_NAME
spec:
  selector:
    matchLabels:
      app: worker # APP_LABEL_NAME # Matches the Service's selector
  serviceName: "worker-service" # "SERVICE_NAME"
  replicas: 3 # NUMBER_OF_REPLICAS
  template:
    metadata:
      labels:
        app: worker # APP_LABEL_NAME
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: blob-store
          image: europe-central2-docker.pkg.dev/blobs-project-449409/repo/blob-store:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50042 # needs to match the worker port
              name: worker
          command: ["./build/bin/worker_server"]
          env:
            - name: MASTERS_COUNT
              value: "3" # needs to match replicas count in master.yaml
            - name: CONTAINER_PORT
              value: "50042"
          resources:
            limits:
              ephemeral-storage: 1Gi
            requests:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 2Gi
#          volumeMounts:
#            - name: www
#              mountPath: CONTAINER_STORAGE_VOLUME_PATH
#  volumeClaimTemplates:
#    - metadata:
#        name: www
#      spec:
#        accessModes: [ "ReadWriteOnce" ]
#        resources:
#          requests:
#            storage: 1Gi